name: apiary doc build
on:
  push:
    branches: [ develop, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -la
          docker build -t apiary_doc_base:latest .
          docker push jaytaph/apiary_doc_base:latest
