name: apiary doc build
on:
  push:
    branches: [ develop, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t jaytaph/apiary-doc-base:latest .
          docker push jaytaph/apiary-doc-base:latest
